// SOS · 신고 안내 (외국인 여행자용) — KO / EN / ZH / JA
// 번호 정보: 112(경찰, 영어·중국어 통역 24시간), 119(소방·구급, 통역 지원), 1330(관광통역안내, 영·중·일 24시간),
// 1345(외국인종합안내센터), 1577-1366(이주여성 긴급지원, 24시간 다국어)

export const PHRASES = [
  { ko: "도와주세요!", rom: "Dowajuseyo!", en: "Help me!", zh: "请帮帮我！", ja: "助けてください！" },
  { ko: "경찰을 불러 주세요.", rom: "Gyeongchareul bulleo juseyo.", en: "Please call the police.", zh: "请帮我报警。", ja: "警察を呼んでください。" },
  { ko: "구급차를 불러 주세요.", rom: "Gugeupchareul bulleo juseyo.", en: "Please call an ambulance.", zh: "请叫救护车。", ja: "救急車を呼んでください。" },
  { ko: "누가 저를 따라와요.", rom: "Nuga jeoreul ttarawayo.", en: "Someone is following me.", zh: "有人在跟踪我。", ja: "誰かについてこられています。" },
  { ko: "화장실에 몰래카메라가 있어요.", rom: "Hwajangsil-e mollae kamera-ga isseoyo.", en: "There is a hidden camera in the restroom.", zh: "厕所里有偷拍摄像头。", ja: "トイレに盗撮カメラがあります。" },
  { ko: "다쳤어요. 아파요.", rom: "Dachyeosseoyo. Apayo.", en: "I'm hurt. I'm in pain.", zh: "我受伤了，很痛。", ja: "けがをしました。痛いです。" },
  { ko: "영어 통역 부탁해요.", rom: "Yeong-eo tongyeok butakaeyo.", en: "English interpreter, please.", zh: "请帮我找中文翻译。", ja: "日本語の通訳をお願いします。", koByLang: { zh: "중국어 통역 부탁해요.", ja: "일본어 통역 부탁해요." }, romByLang: { zh: "Junggugeo tongyeok butakaeyo.", ja: "Ilboneo tongyeok butakaeyo." } },
  { ko: "제 위치는 여기예요.", rom: "Je wichineun yeogiyeyo.", en: "This is where I am.", zh: "我的位置在这里。", ja: "私の居場所はここです。" },
];

export const SOS = {
  ko: {
    nav: "SOS",
    title: "긴급 신고 안내",
    intro: "위험하거나 도움이 필요하면 망설이지 말고 바로 연락하세요. 통화료는 무료예요.",
    police: "경찰", policeSub: "범죄·위협·몰래카메라",
    fire: "소방·구급", fireSub: "부상·응급환자·화재",
    travel: "관광통역", travelSub: "통역·여행 도움 (24시간)",
    langNote: "112·119는 영어·중국어 통역을 연결해 줘요. 말이 안 통하면 1330에 전화해 통역을 부탁하세요.",
    textTitle: "말하기 어렵다면 문자로",
    textBody: "112는 문자(SMS)로도 신고할 수 있어요. 아래 버튼을 누르면 내 위치가 들어간 신고 문자가 준비돼요.",
    textBtn: "112에 문자 신고",
    textMsg: "[긴급신고] 도와주세요. 외국인 여행자입니다.",
    locTitle: "신고할 때 내 위치",
    locBody: "전화로 위치를 물어보면 아래 내용을 읽어주거나 보여주세요.",
    locNear: "가장 가까운 화장실",
    locCopy: "위치 복사", locCopied: "위치를 복사했어요", locUnknown: "위치를 확인할 수 없어요. 주변 간판이나 건물 이름을 알려주세요.",
    toiletTitle: "화장실에서",
    toilet: [
      ["몰래카메라가 의심될 때", "직접 만지지 말고, 안전하면 사진만 찍은 뒤 밖으로 나와 112에 신고하세요."],
      ["누군가 위협하거나 따라올 때", "칸 문을 잠그고 비상벨이 있으면 누르세요. 비상벨은 경찰이나 관리실로 연결될 수 있어요. 바로 112에 전화하세요."],
      ["몸이 아프거나 쓰러진 사람을 봤을 때", "119에 전화하고, 가까운 사람에게 도움을 요청하세요."],
    ],
    streetTitle: "길에서",
    street: [
      ["성추행·폭행·위협", "밝고 사람이 많은 곳(24시간 편의점 등)으로 이동한 뒤 112에 신고하세요."],
      ["도난·분실", "112에 신고하세요. 신고 접수증이 필요하면 가까운 경찰서나 지구대를 찾으세요."],
      ["교통사고·부상", "다친 사람이 있으면 119, 사고 처리는 112에 연락하세요."],
      ["길을 잃었거나 말이 안 통할 때", "1330에 전화하면 통역과 길 안내를 도와줘요."],
    ],
    phrasesTitle: "한국어로 보여주기",
    phrasesBody: "눌러서 크게 보여주거나 소리로 들려주세요.",
    otherTitle: "다른 도움 번호",
    other: [
      ["1345", "외국인종합안내센터 — 체류·생활 상담 (다국어)"],
      ["1577-1366", "이주여성 긴급지원 — 폭력 피해 상담 (24시간, 다국어)"],
    ],
    note: "번호와 지원 언어·시간은 운영기관 사정에 따라 바뀔 수 있어요.",
    speak: "소리로 듣기",
  },
  en: {
    nav: "SOS",
    title: "Emergency help",
    intro: "If you feel unsafe or need help, call right away. These calls are free.",
    police: "Police", policeSub: "Crime, threats, hidden cameras",
    fire: "Fire & Ambulance", fireSub: "Injury, medical emergency, fire",
    travel: "Travel Hotline", travelSub: "Interpreter & travel help (24h)",
    langNote: "112 and 119 can connect an English or Chinese interpreter. If you can't communicate, call 1330 and ask for interpretation.",
    textTitle: "Can't speak? Send a text",
    textBody: "You can report to 112 by text message (SMS). Tap below to open a message that already includes your location.",
    textBtn: "Text 112",
    textMsg: "[EMERGENCY] Please help. I am a foreign traveler.",
    locTitle: "Your location for the call",
    locBody: "If they ask where you are, read out or show this.",
    locNear: "Nearest restroom",
    locCopy: "Copy location", locCopied: "Location copied", locUnknown: "Location unavailable. Describe nearby signs or building names.",
    toiletTitle: "In a restroom",
    toilet: [
      ["You suspect a hidden camera", "Don't touch it. If safe, take a photo, leave the restroom and call 112."],
      ["Someone threatens or follows you", "Lock the stall and press the emergency bell if there is one — it may connect to the police or the management office. Call 112 right away."],
      ["Someone is sick or has collapsed", "Call 119 and ask people nearby for help."],
    ],
    streetTitle: "On the street",
    street: [
      ["Harassment, assault or threats", "Move to a bright, busy place (such as a 24-hour convenience store) and call 112."],
      ["Theft or lost items", "Call 112. For a police report, visit the nearest police station or police box."],
      ["Traffic accident or injury", "Call 119 if anyone is hurt, and 112 for the accident."],
      ["Lost, or can't communicate", "Call 1330 for interpretation and directions."],
    ],
    phrasesTitle: "Show it in Korean",
    phrasesBody: "Tap to show it large or play it aloud.",
    otherTitle: "Other helplines",
    other: [
      ["1345", "Immigration Contact Center — visa & living help (multilingual)"],
      ["1577-1366", "Emergency support for migrant women — violence (24h, multilingual)"],
    ],
    note: "Numbers, languages and hours may change depending on the operating agency.",
    speak: "Play aloud",
  },
  zh: {
    nav: "SOS",
    title: "紧急求助指南",
    intro: "感到危险或需要帮助时，请立即拨打电话。以下电话均免费。",
    police: "警察", policeSub: "犯罪、威胁、偷拍",
    fire: "消防·急救", fireSub: "受伤、急症、火灾",
    travel: "旅游热线", travelSub: "翻译与旅行帮助（24小时）",
    langNote: "112和119可提供英语、中文翻译。如果沟通困难，请拨打1330请求翻译。",
    textTitle: "不方便说话？发短信报警",
    textBody: "可以通过短信(SMS)向112报警。点击下方按钮，会生成含有您位置的报警短信。",
    textBtn: "短信报警 112",
    textMsg: "[紧急求助] 请帮帮我，我是外国游客。",
    locTitle: "报警时您的位置",
    locBody: "被问到位置时，请读出或出示以下内容。",
    locNear: "最近的厕所",
    locCopy: "复制位置", locCopied: "已复制位置", locUnknown: "无法获取位置。请说明附近的招牌或建筑名称。",
    toiletTitle: "在厕所里",
    toilet: [
      ["怀疑有偷拍摄像头", "不要触碰。在安全的情况下拍照，离开厕所后拨打112。"],
      ["有人威胁或跟踪", "锁好隔间门，如有紧急呼叫铃请按下——可能会连接警察或管理处。立即拨打112。"],
      ["有人身体不适或晕倒", "拨打119，并向附近的人求助。"],
    ],
    streetTitle: "在街上",
    street: [
      ["性骚扰、暴力、威胁", "前往明亮、人多的地方（如24小时便利店）后拨打112。"],
      ["被盗或丢失物品", "拨打112。如需报案证明，请前往附近的派出所。"],
      ["交通事故或受伤", "有人受伤请拨打119，事故处理请拨打112。"],
      ["迷路或语言不通", "拨打1330，可提供翻译和路线指引。"],
    ],
    phrasesTitle: "用韩语出示",
    phrasesBody: "点击可放大显示或播放语音。",
    otherTitle: "其他求助电话",
    other: [
      ["1345", "外国人综合咨询中心 — 签证与生活咨询（多语种）"],
      ["1577-1366", "移民女性紧急支援 — 暴力受害咨询（24小时，多语种）"],
    ],
    note: "电话号码、支持语言及时间可能因运营机构而变更。",
    speak: "播放语音",
  },
  ja: {
    nav: "SOS",
    title: "緊急通報ガイド",
    intro: "危険を感じたり助けが必要なときは、すぐに電話してください。通話は無料です。",
    police: "警察", policeSub: "犯罪・脅迫・盗撮",
    fire: "消防・救急", fireSub: "けが・急病・火災",
    travel: "観光通訳", travelSub: "通訳・旅行サポート（24時間）",
    langNote: "112・119は英語・中国語の通訳につなげます。言葉が通じない場合は1330に電話して通訳を頼んでください（日本語24時間）。",
    textTitle: "話せないときはSMSで",
    textBody: "112にはSMSでも通報できます。下のボタンを押すと、現在地入りの通報メッセージが用意されます。",
    textBtn: "112にSMS通報",
    textMsg: "[緊急通報] 助けてください。外国人旅行者です。",
    locTitle: "通報時の現在地",
    locBody: "場所を聞かれたら、以下を読み上げるか見せてください。",
    locNear: "最寄りのトイレ",
    locCopy: "位置をコピー", locCopied: "位置をコピーしました", locUnknown: "位置情報を取得できません。近くの看板や建物名を伝えてください。",
    toiletTitle: "トイレで",
    toilet: [
      ["盗撮カメラが疑われるとき", "触らずに、安全なら写真だけ撮ってトイレを出て112に通報してください。"],
      ["誰かに脅されたり、つけられたとき", "個室の鍵をかけ、非常ベルがあれば押してください（警察や管理室につながる場合があります）。すぐ112に電話してください。"],
      ["体調不良や倒れている人を見たとき", "119に電話し、近くの人に助けを求めてください。"],
    ],
    streetTitle: "路上で",
    street: [
      ["痴漢・暴行・脅迫", "明るく人の多い場所（24時間コンビニなど）へ移動して112に通報してください。"],
      ["盗難・紛失", "112に通報してください。証明書が必要なら近くの警察署・交番へ。"],
      ["交通事故・けが", "けが人がいれば119、事故処理は112に連絡してください。"],
      ["道に迷った・言葉が通じない", "1330に電話すると通訳と道案内を手伝ってくれます。"],
    ],
    phrasesTitle: "韓国語で見せる",
    phrasesBody: "タップすると大きく表示、または音声で再生できます。",
    otherTitle: "その他の相談窓口",
    other: [
      ["1345", "外国人総合案内センター — 在留・生活相談（多言語）"],
      ["1577-1366", "移住女性緊急支援 — 暴力被害相談（24時間・多言語）"],
    ],
    note: "番号・対応言語・時間は運営機関の事情により変わる場合があります。",
    speak: "音声で再生",
  },
};
